// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoj4FoCQR7sZp4SRIgyy4hT87Qy7Hpoho',
    appId: '1:326896452261:web:a6a19791340662f6ed434c',
    messagingSenderId: '326896452261',
    projectId: 'prontochat-3b974',
    authDomain: 'prontochat-3b974.firebaseapp.com',
    storageBucket: 'prontochat-3b974.firebasestorage.app',
    measurementId: 'G-KFXW4WLR4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyf-gBNyXbj_bO8UbbaZknlTYxPfLPNw',
    appId: '1:326896452261:android:9e836a89a0bc2dd2ed434c',
    messagingSenderId: '326896452261',
    projectId: 'prontochat-3b974',
    storageBucket: 'prontochat-3b974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9tXJWLj7GsXlGA7JAuCppBrPCXVka4I',
    appId: '1:326896452261:ios:3cd117dcc0e434e3ed434c',
    messagingSenderId: '326896452261',
    projectId: 'prontochat-3b974',
    storageBucket: 'prontochat-3b974.firebasestorage.app',
    iosBundleId: 'com.example.prontoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9tXJWLj7GsXlGA7JAuCppBrPCXVka4I',
    appId: '1:326896452261:ios:3cd117dcc0e434e3ed434c',
    messagingSenderId: '326896452261',
    projectId: 'prontochat-3b974',
    storageBucket: 'prontochat-3b974.firebasestorage.app',
    iosBundleId: 'com.example.prontoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoj4FoCQR7sZp4SRIgyy4hT87Qy7Hpoho',
    appId: '1:326896452261:web:39e5d6e12bd96476ed434c',
    messagingSenderId: '326896452261',
    projectId: 'prontochat-3b974',
    authDomain: 'prontochat-3b974.firebaseapp.com',
    storageBucket: 'prontochat-3b974.firebasestorage.app',
    measurementId: 'G-GRZ96CGPLY',
  );

}